Repository ThePhar/archipelago.js, pull requests merged in 2024-11, with the labels that each got.

#193 Set ItemManager index to correct value after ReceivedItems
  src/managers/ItemsManager.ts
Labels: bug

#194 Don't report connection still alive after close without Client.disconnect
  src/Client.ts
Labels: bug

#191 Add `slot_data` connect argument
  src/Client.ts
  src/packets/ConnectPacket.ts
  src/types/ConnectionInformation.ts
Labels: bug

#207 Update build system, readme, and add debug logging to data storage
  README.md
  build.mjs
  package-lock.json
  package.json
  src/managers/DataManager.ts
  typedoc.json
Labels: is: enhancement, affects: legacy

#211 archipelago.js@2.0.0-rc6 Changes
  guides/getting_started.md
  package.json
  src/classes/Client.ts
  src/classes/Hint.ts
  src/classes/MessageNode.ts
  src/classes/PackageMetadata.ts
  src/classes/managers/ItemsManager.ts
  src/classes/managers/MessageManager.ts
  src/classes/managers/PlayersManager.ts
  src/classes/managers/SocketManager.ts
  src/constants.ts
  src/events/MessageEvents.ts
  src/events/SocketEvents.ts
  src/index.ts
  typedoc.json
Labels: is: bug, is: documentation, is: enhancement

#214 archipelago.js@2.0.1 Patches
  package.json
  src/api/constants.ts
  src/classes/Client.ts
  src/classes/Item.ts
  src/classes/managers/DataStorageManager.ts
  src/classes/managers/DeathLinkManager.ts
  src/classes/managers/MessageManager.ts
  src/classes/managers/PlayersManager.ts
  src/classes/managers/SocketManager.ts
  src/constants.ts
  src/index.ts
Labels: is: bug, is: enhancement

#215 Change package.json `homepage` to https://archipelago.js.org
  package.json
Labels: is: documentation

#216 Update some typing and minor doc tweaks
  README.md
  assets/api.css
  assets/favicon.png
  assets/icon_small.png
  build.mjs
  guides/creating.md
  guides/creating/example_1.gif
  guides/getting_started.md
  guides/installation.md
  guides/introduction.md
  guides/introduction/doc_improvements.md
  guides/placeholder.md
  package.json
  pnpm-lock.yaml
  src/classes/Client.ts
  src/classes/IntermediateDataOperation.ts
  src/constants.ts
  src/test.ts
  typedoc.json
Labels: is: bug, is: documentation

#218 Patch improper export, update some jsdoc/devDependencies, and remove testing code
  .gitignore
  package.json
  pnpm-lock.yaml
  src/classes/Player.ts
  src/classes/managers/PlayersManager.ts
  src/constants.ts
  src/test.ts
  tsconfig.json
Labels: is: bug, is: dependencies

#219 Exclude new files from npm published builds as they're only relevant for documentation/local testing
  .npmignore
  package.json
  src/constants.ts
Labels: is: bug
